### ISSUE TITLE
Add Join and Except operations

### ISSUE THREAD

**Issue by t94j0** [hamba/slices#1]
Hey, I love this project. I made something similar to this a couple years back, but your implementation is much more robust. I implemented the Intersection and Except operations and would love to see something similar here.

**Intersection** - Take two slices and return values that are the same in both slices

a := []int{1, 2, 3}
b := []int{2, 3, 4}
Intersection(a, b)
returns: [2 3]

**Except** - Take two slices and return values that only appear in the first slice

a := []int{1, 2, 5}
b := []int{2, 3, 4}
Except(a, b)
returns: [1 5]

My code is [here]. Feel free to use whatever you'd like. Super excited for your project!

[here]: https://github.com/t94j0/array

**Comment by nrwiersma** [comment]
Hey,

Thanks for the suggestions. Will gladly add them in.

**Comment by nrwiersma** [comment]
What is the expectation of these functions, to return a new slice, or to modify one of the existing slices?

**Comment by t94j0** [comment]
I like returning a new slice, but I could see modifying the existing slice for memory performance reasons.
